# Generated by Django 6.0 on 2025-12-31 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('CE', 'Civil Engineering'), ('CSE', 'Computer Science Engineering'), ('EEE', 'Electrical Engineering'), ('ECE', 'Electronics and Communications Engineering'), ('ISE', 'Information Science Engineering'), ('ME', 'Mechanical Engineering'), ('BS', 'Basic Science')], max_length=3)),
                ('email', models.EmailField(default='', max_length=50)),
                ('contact', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='room_code',
        ),
        migrations.RemoveField(
            model_name='livesession',
            name='subject_name',
        ),
        migrations.AddField(
            model_name='livesession',
            name='room_number',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livesession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('course_name', models.CharField(default='', max_length=50)),
                ('total_classes', models.IntegerField(default=0)),
                ('semester', models.IntegerField(choices=[(1, '1th'), (2, '2th'), (3, '3th'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')], default=1)),
                ('teacher_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.teacherprofile')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.department')),
            ],
        ),
        migrations.AddField(
            model_name='livesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course'),
        ),
    ]
