# Generated by Django 6.0 on 2025-12-31 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_department_remove_livesession_room_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin', models.CharField(max_length=10, unique=True)),
                ('semester', models.IntegerField(choices=[(1, '1th'), (2, '2th'), (3, '3th'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')], default=1)),
                ('phone', models.CharField(default='', max_length=12)),
                ('parent_phone', models.CharField(default='', max_length=12)),
                ('address', models.CharField(max_length=500, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('image', models.ImageField(default='default.png', upload_to='students/')),
                ('last_digit', models.IntegerField(editable=False, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
