# Generated by Django 4.2 on 2023-04-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_alter_homework_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(null=True),
        ),
    ]
