# Generated by Django 4.2 on 2023-04-12 03:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactus'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursequiz',
            name='course',
            field=models.ForeignKey(default='course', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.course'),
        ),
    ]
