# Generated by Django 6.0 on 2025-12-31 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classroom', '0002_department_remove_livesession_room_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_students_present', models.IntegerField(default=0)),
                ('attendance_percentage', models.FloatField(default=0.0)),
                ('interaction_score', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='classroom.livesession')),
            ],
        ),
    ]
