# Generated by Django 4.1.7 on 2023-03-30 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_face', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(max_length=70)),
                ('date', models.DateField()),
                ('phone', models.BigIntegerField(primary_key=True, serialize=False)),
                ('parentphone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(max_length=254)),
                ('roomno', models.IntegerField()),
                ('address', models.CharField(max_length=500, null=True)),
                ('college', models.CharField(max_length=200)),
                ('course', models.CharField(max_length=200, null=True)),
                ('hostelname', models.CharField(choices=[('None', 'None'), ('cvr', 'cvr'), ('asr', 'asr'), ('vvk', 'vvk'), ('vsr', 'vsr'), ('sac', 'sac'), ('dvr', 'dvr')], default='employee', max_length=20, null=True)),
                ('hosteltype', models.CharField(choices=[('None', 'None'), ('AC', 'AC'), ('Non AC', 'Non AC')], default='non_ac', max_length=20, null=True)),
                ('present', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('shift', models.TimeField(default=datetime.time(20, 45))),
            ],
        ),
    ]
