# Generated by Django 4.2 on 2023-04-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_coursecategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3) Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2) Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '4) Students'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name_plural': '1) Teachers'},
        ),
    ]
