# Generated by Django 4.2 on 2023-04-11 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address',
        ),
    ]
