# Generated by Django 4.2 on 2023-04-11 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_teacher_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
    ]
